### ISSUE TITLE
Proteus Gate Output Occasionally Stuck At High

### ISSUE THREAD

**Issue by McGroggin** [abluenautilus/SeasideModularVCV#1]
VCV Rack Pro v2.1.2 as standalone
Windows 10 current
Intel i7-8700K
Nvidia GTX 1070 8GB VRAM
16GB Ram

As mentioned by another user in the Proteus announcement thread on the VCV community forum, I too have experienced the gate output for Proteus locking up and outputting a steady 10v.

For me it only occurred at the initialization of a new Proteus module being added to the rack and did not occur randomly during operation. As of this writing I have experienced this problem 1 time in 3 total patches over the course of a single session.

I created a new patch using Proteus that ran for four hours without issue, while experimenting with it's parameters throughout.

I then cleared the patch and started a new one with a new instance of Proteus. Starting conditions were the same as far as clock, bpm and audio I/O etc. I did not re-start Rack. I re-opened my base template consisting of a MindMeld mixer, Clocked by Impromptu and the core Audio 16 module.

After creating my first voice and connecting it to Proteus I noticed that the gate output was only putting out a constant 10v. Connecting it to the scope confirmed this.

The following actions did NOT correct the issue:

- Disconnecting all cables and reconnecting them again.
- Changing parameters, including Gate Length
- Repeatedly hitting the new sequence button and chanting "come on - come on"
- Duplicating the Proteus module
- Re-initializing the module from it's context menu
- Adding a new instance of the module
- Clearing the patch and starting from a new template

The following action DID correct the issue:

- Closing VCV Rack completely, loading it up again with an empty (base template) patch and adding Proteus from the local library.

I did not try simply closing Rack and re-opening a patch with the problematic Proteus though as closing rack was the last resort so I don't know if that would have corrected the problem or not.

**Comment by abluenautilus** [comment]
Thanks so much for the detailed report....

Disappointed that chanting "come on come on" did not solve the problem. :D

I haven't been able to replicate this issue yet myself, so I'm feeling around in the dark a bit, but I do have some ideas to try that might prevent it.

**Comment by ContemporaryInsanity** [comment]
Confirmed on rack 2.0.6 linux.
Can also confirm that simply closing & reopening patch gets the gates working again, so far.

**Comment by abluenautilus** [comment]
Please let me know if version 2.1 solves this issue for you, thanks!

**Comment by McGroggin** [comment]
I have just spent the last hour or so trying to recreate the open gate issue. It seems to have been resolved with this last version.

Thank you @abluenautilus
