### ISSUE TITLE
sequences not saving across patch reload for some users

### ISSUE THREAD

**Issue by abluenautilus** [abluenautilus/SeasideModularVCV#11]
User wemizio on VCV forum reports that sequences are empty when reloading a patch on VCV 2.3 windows 7.

**Comment by abluenautilus** [comment]
Cannot reproduce this on Mac OSX.

**Comment by ZwergNaseXXL** [comment]
Don't know if it's the same issue, but I'm seeing something similar. For me, the sequences are saved, but after re-opening VCV they play back with a very low density. Not all of them, but most of them. Sometimes only one or two notes. When I wiggle the density knob a little, they play with more notes. Re-saving them in this higher density state doesn't help though, on the next reload they are back to low density, even though the density knob is at about 75%.
(Windows 10, latest Rack and plugin versions)
Attached two JSON files retrieved by copy/pasting the selected modules. The Proteus data looks different between the two, ProteusX is still the same.
[AfterLoad.txt](https://github.com/abluenautilus/SeasideModularVCV/files/11008156/AfterLoad.txt)
[AfterWiggle.txt](https://github.com/abluenautilus/SeasideModularVCV/files/11008158/AfterWiggle.txt)

**Comment by abluenautilus** [comment]
Hopefully fixed in 2.4.2

**Comment by ZwergNaseXXL** [comment]
Sorry for the late feedback. It seems to work fine with ProteusX attached, but now I get the same issue without ProteusX. 

After restarting VCV, Proteus appears to not play anything (even though the LEDs are moving), until you a) wiggle the density knob, b) press the new sequence button or c) Proteus creates a new sequence itself. So with lock mode engaged, there's no output until you manually a) or b).
