### ISSUE TITLE
Suggestion for tiny performance improvement

### ISSUE THREAD

**Issue by cosinekitty** [abluenautilus/SeasideModularVCV#4]
This is really trivial, but... these assignments could be moved inside the `if` above them.

https://github.com/abluenautilus/SeasideModularVCV/blob/76d6815f34fbcdb1ebebabb90e1196db94662b62/src/Jawari.cpp#L180

They don't need to be executed unless one of the values has changed.

**Comment by abluenautilus** [comment]
No problem is too small! ty.

Fixed.
