### ISSUE TITLE
.gitignore does not ignore the plugin.dll

### ISSUE THREAD

**Issue by squinkylabs** [abluenautilus/SeasideModularVCV#7]
You can see here that git is tracking the final build file, which should not be checked in:

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/Jawari.cpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        inc/autowah4.hpp
        plugin.dll

**Comment by abluenautilus** [comment]
plugin.dll added to .gitignore
