### ISSUE TITLE
I have a version that uses much less CPU.

### ISSUE THREAD

**Issue by squinkylabs** [abluenautilus/SeasideModularVCV#8]
If you would like it, we should arrange how best to deliver it to you.

ATM it's sitting in a fork where I modified it on the "master" branch. https://github.com/squinkylabs/SeasideModularVCV

**Comment by abluenautilus** [comment]
Wow amazing. 

A quick look seems like you rewrote the autowah in autowah4. Is there anything else you did?

**Comment by abluenautilus** [comment]
I guess the diffs tell me that. Looks like just autowah was the main issue. I can probably just copy that file in and make the changes in Jawari.cpp as well.

**Comment by squinkylabs** [comment]
Yeah, that's probably best. All the stuff in Jawari.cpp should be inside #ifdef _FAST.

**Comment by squinkylabs** [comment]
And, yeah, all I did was re-write the AutoWah. The other things didn't  use a ton of CPU, so they really weren't going after. Surprised I got more than 4x by using SIMD, but maybe I'm using a fast approximation in there? pow and cosf were both pretty slow.

**Comment by abluenautilus** [comment]
new version leaves out autowah altogether.

**Comment by squinkylabs** [comment]
ah, that's the best solution!
